# Generated by Django 4.1.5 on 2023-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('designation', models.CharField(max_length=50, verbose_name='Cargo')),
                ('photo', models.ImageField(upload_to='photos/%d/%m/%Y/', verbose_name='Imagem')),
                ('facebook_link', models.URLField(max_length=100, verbose_name='Facebook')),
                ('twitter_link', models.URLField(max_length=100, verbose_name='Twitter')),
                ('instagran_link', models.URLField(max_length=100, verbose_name='Instagram')),
                ('linkedin_link', models.URLField(max_length=100, verbose_name='Lindedin')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
        ),
    ]
