# Generated by Django 4.1.5 on 2023-01-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_team_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
