# Generated by Django 4.1.5 on 2023-01-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_servico_descriptions_alter_servico_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descriptions',
            field=models.CharField(max_length=200, verbose_name='descrição'),
        ),
    ]
