# Generated by Django 4.1.5 on 2023-01-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco',
            field=models.ImageField(default=0, upload_to='', verbose_name='Preço'),
        ),
    ]
