# Generated by Django 4.1.5 on 2023-01-31 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_plano_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='plano',
            new_name='pacote',
        ),
    ]
