# Generated by Django 4.1.5 on 2023-01-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_plano_plano_pacote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Pacote', 'verbose_name_plural': 'Pacotes'},
        ),
    ]
